#!/usr/bin/env python

import pandas as pd
import sys
import argparse


def parse_row(strparse):
    row = strparse[1:-1].split("> <")
    return row

def parse_list(lostr):
    lol = []
    largest_schema = None
    len_largest = 0
    for i in range(0,500):
        list1 = parse_row(lostr[i])
        if len(list1) > len_largest:
            len_largest = len(list1)
            largest_schema = list1
        lol.append(list1)
        if i + 1 == len(lostr):
            break
    return lol, largest_schema

def create_table(lol, largest_schema):
    fields = [[] for i in largest_schema]
    for i in lol:
        for x in range(0,len(largest_schema)):
            if type(infer_type(largest_schema[x])) == type(infer_type(i[x])):
                fields[x].append(infer_type(i[x]))
            else:
                fields[x].append(None)
            if x + 1 == len(i):
                break
    return pd.DataFrame(fields).transpose()

def parsefile(f,start=0,end=100):
    f = open(f,"r")
    f.seek(start)
    line1 = f.read(end)
    if start > 0:
        firstbreak = line1[0:end].index("\n")
        line1 = line1[firstbreak+1:len(line1)]
    line1 = line1.split("\n")
    if start > 0:
        line1 = line1[0:-1]
    return [x.strip() for x in line1]


def infer_type(x):
    if x == "":
        return None
    elif x[0] == "\"" and x[-1] == "\"":
        return x[1:-1]
    elif x == "1":
        return True
    elif x == "0":
        return False
    elif x[0] == "+":
        if x[1] in "1234567890":
            if "." in x:
                return float(x[1:len(x)])
            else:
                return int(x[1:len(x)])
    elif x[0] == "-":
        if x[1] in "1234567890":
            if "." in x:
                return float(x[1:len(x)])*-1
            else:
                return int(x[1:len(x)])*-1
    elif x[0] in "1234567890":
        if "." in x:
            return float(x[0:len(x)])
        else:
            return int(x[0:len(x)])
    else:
        return x


def print_col_type(df,col):
    value = None
    for i in df[col]:
        if i is not None:
            value = i
            break
    return type(value)

def is_missing_idx(df,col,offset):
    if df[col][offset] is None:
        return True
    else:
        return False

def print_col_idx(df,col,offset):
    return df[col][offset]

def main(argv):

    #Add all command line arguments
    parser = argparse.ArgumentParser(description='Short sample app')
    parser.add_argument('-f', action="store",
                        dest="f",default = False)
    parser.add_argument('-from', action="store",
                        dest="from1")
    parser.add_argument('-len', action="store",
                        dest="len")
    parser.add_argument('-print_col_type', action="store",
                        dest="print_col_type")
    parser.add_argument('-is_missing_idx', action="store",
                        dest="is_missing_idx", nargs='*')
    parser.add_argument('-print_col_idx', action="store",
                        dest="print_col_idx", nargs="*")

    #parse the arguments
    x = parser.parse_args(argv)
    #parse the file
    f = parsefile(x.f, int(x.from1), int(x.len))
    list2 = parse_list(f)
    table2 = create_table(list2[0],list2[1])
    if hasattr(x,"print_col_type") and x.print_col_type is not None:
        print(print_col_type(table2,int(x.print_col_type)))
    if hasattr(x,"is_missing_idx") and x.is_missing_idx is not None:
        print(is_missing_idx(table2,int(x.is_missing_idx[0]),int(x.is_missing_idx[1])))
    if hasattr(x,"print_col_idx") and x.print_col_idx is not None:
        print(print_col_idx(table2,int(x.print_col_idx[0]),int(x.print_col_idx[1])))
if __name__ == "__main__":
   main(sys.argv[1:])